### ISSUE TITLE
Process mapping.json and provide mapping summaries

### ISSUE THREAD

**Issue by VimCommando** [elastic/esdiag#118]
Bringing in the whole mapping isn't very efficient, nor useful. However, a summary metrics is _very_ useful.

One of the most useful Analzyer.next visualizations is the simple breakdown of how many fields of each type there are. Having the field type and count in the index stats has been a long open request:
https://github.com/elastic/elasticsearch/issues/68947

As a first pass, all I really want is to enrich the existing `index_stats` outputs from a new `MappingStats` lookup:

```yml
mappings:
    dynamic: "strict"
    _meta: Object // Passed through from source mappings.json file
    field:
        count: 47
        types:
            text: 5
            keyword: 20
            long: 17
            float: 4
            wildcard: 1
```

The `mappings` object will be added to the `metrics-index-esdiag` data stream, where the `IndicesStats` processor will do a lookup to `MappingStats` by index name.
